// Собран скриптом скрипты/собрать-отчёт-01.py из заметок требований.
// Таблицы повторяют сетку сданного docx: альбомный лист, TableGrid, цвета ячеек.
#set page(
  flipped: true,
  margin: (left: 15mm, right: 15mm, top: 14mm, bottom: 14mm),
)

= Верификация исходных требований

Цветовое кодирование совпадает со сданным отчётом. #text(fill: rgb("#FF0000"))[Красным] выделены фрагменты, которые предлагается удалить или уточнить. #text(fill: rgb("#00B0F0"))[Голубым] записаны вопросы владельцу продукта. #text(fill: rgb("#00A000"))[Зелёным] записаны ответы, предложенные командой: владелец продукта их ещё не подтвердил. #text(fill: rgb("#0000FF"), weight: "bold")[Синим полужирным] дана новая формулировка требования.

#[
  #set text(size: 7pt)
  #set par(justify: false, first-line-indent: (amount: 0pt, all: true), leading: 0.65em, spacing: 0.4em)
  #table(
    columns: (1050fr, 1780fr, 3340fr, 3340fr, 3340fr, 3340fr),
    stroke: 0.5pt,
    inset: 4pt,
    align: left + top,
    table.header(
      repeat: true,
      table.cell(fill: rgb("#D9EAF7"), align: center + horizon)[#text(weight: "bold")[№]],
      table.cell(fill: rgb("#D9EAF7"), align: left + top)[#text(weight: "bold")[Группа]],
      table.cell(fill: rgb("#D9EAF7"), align: left + top)[#text(weight: "bold")[Исходное требование (красным – уточняемые фразы)]],
      table.cell(fill: rgb("#D9EAF7"), align: left + top)[#text(weight: "bold")[Вопрос владельцу продукта]],
      table.cell(fill: rgb("#D9EAF7"), align: left + top)[#text(weight: "bold")[Ответ владельца продукта (предлагаемый)]],
      table.cell(fill: rgb("#D9EAF7"), align: left + top)[#text(weight: "bold")[Новая формулировка требования]],
    ),
    table.cell(align: center + horizon, breakable: false)[REQ-001], table.cell(align: left + top, breakable: false)[Системные характеристики], table.cell(align: left + top, breakable: false)[Реализуемый веб-сайт обладает адаптивно-отзывчивой версткой, обеспечивающей #text(fill: rgb("#FF0000"))[комфортное отображение] информации на различных устройствах, принадлежащих трем основным категориям: компьютер, планшет, смартфон.], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Что понимается под «комфортным отображением» и при каких размерах области просмотра должна проверяться адаптивность?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Интерфейс должен оставаться пригодным для работы без горизонтальной прокрутки при ширине области просмотра от 360 px. Контрольные диапазоны: 360–767 px, 768–1023 px, 1024 px и более.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Веб-сайт должен адаптировать компоновку всех страниц к ширине области просмотра 360–767 px, 768–1023 px и 1024 px и более, не допуская горизонтальной прокрутки страницы.]],
    table.cell(align: center + horizon, breakable: false)[REQ-002], table.cell(align: left + top, breakable: false)[Системные характеристики], table.cell(align: left + top, breakable: false)[Разработанный веб-сайт должен являться #text(fill: rgb("#FF0000"))[кроссплатформенным], т. е. должен обладать #text(fill: rgb("#FF0000"))[адекватным отображением контента] #text(fill: rgb("#FF0000"))[вне зависимости от операционной системы клиента].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Какие операционные системы и версии необходимо поддерживать и по какому критерию определяется корректность работы?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Windows 10/11, macOS 13 и новее, Android 12 и новее, iOS 16 и новее; на каждой платформе должны быть доступны все пользовательские функции и не должно быть критических дефектов отображения.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Веб-сайт должен обеспечивать доступность всех пользовательских функций и корректное отображение интерфейса в поддерживаемых браузерах на Windows 10/11, macOS 13 и новее, Android 12 и новее и iOS 16 и новее.]],
    table.cell(align: center + horizon, breakable: false)[REQ-003], table.cell(align: left + top, breakable: false)[Системные характеристики], table.cell(align: left + top, breakable: false)[Разработанный веб-сайт должен являться кроссбраузерным, т. е. должен корректно отображаться и функционировать #text(fill: rgb("#FF0000"))[во всех популярных и часто используемых браузерах].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Какие именно браузеры и какие версии считаются поддерживаемыми?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Google Chrome, Microsoft Edge, Mozilla Firefox и Safari – текущая и предыдущая стабильные версии на момент приемочного тестирования.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Веб-сайт должен корректно отображаться и предоставлять все пользовательские функции в текущей и предыдущей стабильных версиях Google Chrome, Microsoft Edge, Mozilla Firefox и Safari.]],
    table.cell(align: center + horizon, breakable: false)[REQ-004], table.cell(align: left + top, breakable: false)[Системные характеристики], table.cell(align: left + top, breakable: false)[Веб-сайт должен разрабатываться с использованием #text(fill: rgb("#FF0000"))[современных технологий и стандартов формата], #text(fill: rgb("#FF0000"))[например стандарта W3C], а также с использованием следующего стека: #text(fill: rgb("#FF0000"))[HTML, CSS, JS] (клиентской части).], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Какие конкретно технологии, версии стандартов и критерии соответствия W3C требуются для клиентской части?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[HTML5, CSS и JavaScript стандарта ECMAScript 2015 или новее; итоговая HTML-разметка должна проходить проверку W3C Markup Validation Service без ошибок.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Веб-сайт должен использовать в клиентской части HTML5, CSS и JavaScript стандарта ECMAScript 2015 или новее, а HTML-разметка должна проходить проверку W3C Markup Validation Service без ошибок.]],
    table.cell(align: center + horizon, breakable: false)[REQ-005], table.cell(align: left + top, breakable: false)[Атрибуты качества], table.cell(align: left + top, breakable: false)[Скорость отклика сайта должна обеспечивать #text(fill: rgb("#FF0000"))[обработку данных не менее 5Мб/с] на аппаратном обеспечении, эквивалентном следующему: #text(fill: rgb("#FF0000"))[процессор i7, 8 Гб оперативной памяти].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Что требуется измерять: пропускную способность или время отклика? Указанное оборудование относится к серверу или клиенту? При какой нагрузке проводится проверка?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Контролируется время отклика страницы расписания. Не менее 95% запросов должны завершаться не более чем за 2 секунды при 100 одновременных пользователях на тестовом сервере уровня Intel Core i7 и 8 ГБ ОЗУ.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Веб-сайт должен формировать и возвращать страницу расписания не более чем за 2 секунды для не менее 95% запросов при нагрузке 100 одновременных пользователей на тестовом сервере уровня Intel Core i7 и 8 ГБ ОЗУ.]],
    table.cell(align: center + horizon, breakable: false)[REQ-006], table.cell(align: left + top, breakable: false)[Атрибуты качества], table.cell(align: left + top, breakable: false)[Показатель сервиса «#text(fill: rgb("#FF0000"))[Page Speed]» должен находиться #text(fill: rgb("#FF0000"))[в зеленой зоне] #text(fill: rgb("#FF0000"))[для всех основных критериев] анализа веб-сайта, #text(fill: rgb("#FF0000"))[с целью оптимизации скорости, производительности и дальнейшего продвижения].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Какой инструмент PageSpeed используется, какие категории проверяются, какой числовой порог соответствует «зеленой зоне» и для каких страниц проводится проверка?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Google PageSpeed Insights / Lighthouse; публичные страницы «Главная» и «Расписание» проверяются в режимах Mobile и Desktop; оценки Performance, Accessibility, Best Practices и SEO должны быть не ниже 90.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Веб-сайт должен получать в Google Lighthouse не менее 90 баллов по категориям Performance, Accessibility, Best Practices и SEO для публичных страниц «Главная» и «Расписание» в режимах Mobile и Desktop.]],
    table.cell(align: center + horizon, breakable: false)[REQ-007], table.cell(align: left + top, breakable: false)[Атрибуты качества], table.cell(align: left + top, breakable: false)[Веб-сайт должен демонстрировать #text(fill: rgb("#FF0000"))[стабильную и производительную работу] #text(fill: rgb("#FF0000"))[с большим потоком пользователей], #text(fill: rgb("#FF0000"))[вне зависимости от вероятных сторонних негативных факторов].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Какое число одновременных пользователей считается большим потоком, как измеряется стабильность и какие внешние факторы входят в область ответственности системы?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Нагрузочный тест – 200 одновременных пользователей в течение 30 минут; доля ответов HTTP 5xx не более 1%, серверное приложение не должно аварийно завершаться. Сбои внешней сети и сторонних сервисов не включаются в гарантию.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Веб-сайт должен обслуживать 200 одновременных пользователей в течение 30 минут без аварийного завершения серверного приложения и с долей ответов HTTP 5xx не более 1%.]],
    table.cell(align: center + horizon, breakable: false)[REQ-008], table.cell(align: left + top, breakable: false)[Пользовательские требования], table.cell(align: left + top, breakable: false)[Возможность отображения информации на веб-сайте #text(fill: rgb("#FF0000"))[на языке комфортном для основной целевой аудитории] ресурса, в данном случае #text(fill: rgb("#FF0000"))[необходимо использовать русский и английский язык].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Должен ли пользователь самостоятельно переключать язык и какие элементы сайта необходимо переводить?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Пользователь вручную выбирает русский или английский язык; переводятся элементы навигации, подписи полей, кнопки и системные сообщения.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Пользователь должен иметь возможность выбрать русский или английский язык для отображения элементов навигации, подписей полей, кнопок и системных сообщений веб-сайта.]],
    table.cell(align: center + horizon, breakable: false)[REQ-009], table.cell(align: left + top, breakable: false)[Пользовательские требования], table.cell(align: left + top, breakable: false)[Возможность #text(fill: rgb("#FF0000"))[быстрого] просмотра #text(fill: rgb("#FF0000"))[необходимой информации].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Какая именно информация должна быть доступна и по какому измеримому критерию просмотр считается быстрым?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Основная информация – расписание выбранной учебной группы на выбранную дату; пользователь должен получать его не более чем за три действия интерфейса от главной страницы.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Пользователь должен получать расписание выбранной учебной группы на выбранную дату не более чем за три действия интерфейса от главной страницы.]],
    table.cell(align: center + horizon, breakable: false)[REQ-010], table.cell(align: left + top, breakable: false)[Пользовательские требования], table.cell(align: left + top, breakable: false)[Возможность получения #text(fill: rgb("#FF0000"))[какой-либо дополнительной информации] о размещении учебных корпусов, аудиторий и #text(fill: rgb("#FF0000"))[административной информации] об образовательном учреждении.], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Какой конкретно состав дополнительной и административной информации должен быть доступен пользователю?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Название и адрес учебного корпуса, номер аудитории, а также контактный телефон и адрес электронной почты администрации образовательного учреждения.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Пользователь должен иметь возможность просматривать название и адрес учебного корпуса, номер аудитории, контактный телефон и адрес электронной почты администрации образовательного учреждения.]],
    table.cell(align: center + horizon, breakable: false)[REQ-011], table.cell(align: left + top, breakable: false)[Ограничения], table.cell(align: left + top, breakable: false)[Редактирование и добавление информации касательно расписаний занятий допускается только #text(fill: rgb("#FF0000"))[авторизированными пользователями], #text(fill: rgb("#FF0000"))[обладающими правами «Администратора»].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Кто именно может добавлять и редактировать расписание и что происходит с пользователями без административных прав?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Добавление и редактирование доступны только после аутентификации пользователю с ролью «Администратор»; остальные пользователи имеют только доступ к просмотру опубликованной информации.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Система должна разрешать добавление и редактирование информации о расписании только аутентифицированному пользователю с ролью «Администратор».]],
    table.cell(align: center + horizon, breakable: false)[REQ-012], table.cell(align: left + top, breakable: false)[Ограничения], table.cell(align: left + top, breakable: false)[Разрабатываемое приложение #text(fill: rgb("#FF0000"))[должны быть защищено] и #text(fill: rgb("#FF0000"))[функционировать в соответствии HTTPS протоколу безопасности передачи данных].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Должен ли весь обмен данными выполняться по HTTPS, какая минимальная версия TLS требуется и как обрабатываются обращения по HTTP?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Весь клиент-серверный обмен выполняется по HTTPS с TLS 1.2 или новее; обращения по HTTP перенаправляются на HTTPS.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Система должна передавать все данные между клиентом и сервером по HTTPS с использованием TLS 1.2 или новее и перенаправлять обращения по HTTP на HTTPS.]],
    table.cell(align: center + horizon, breakable: false)[REQ-013], table.cell(align: left + top, breakable: false)[Заказчики], table.cell(align: left + top, breakable: false)[Сервис решает #text(fill: rgb("#FF0000"))[проблемы] #text(fill: rgb("#FF0000"))[заказчика].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[Кто заказчик и чьи проблемы решает сервис?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Университеты, школы, в том числе онлайн-школы, и колледжи.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Система должна предоставлять актуальное расписание занятий университетам, школам, в том числе онлайн-школам, и колледжам.]],
    table.cell(align: center + horizon, breakable: false)[REQ-014], table.cell(align: left + top, breakable: false)[Ограничения], table.cell(align: left + top, breakable: false)[Сервис предоставляется заказчику #text(fill: rgb("#FF0000"))[в виде лицензии на платформу поставщика или в виде сайта, который заказчик ставит у себя].], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00B0F0"))[В каком виде предоставляется сервис: лицензия на использование платформы поставщика или сайт, который заказчик ставит у себя?]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#00A000"))[Self-host: сайт, который заказчик разворачивает у себя.]], table.cell(align: left + top, breakable: false)[#text(fill: rgb("#0000FF"), weight: "bold")[Заказчик должен устанавливать сайт сервиса на своей площадке. Поставка в виде лицензии на платформу, размещённую у поставщика, не используется.]],
  )
]

== Табличное представление требований, шаг 1

#[
  #set text(size: 8pt)
  #set par(justify: false, first-line-indent: (amount: 0pt, all: true), leading: 0.65em, spacing: 0.4em)
  #table(
    columns: (1050fr, 1660fr, 3367fr, 2128fr, 3066fr, 4917fr),
    stroke: 0.5pt,
    inset: 4pt,
    align: left + top,
    table.header(
      repeat: true,
      table.cell(fill: rgb("#E2F0D9"), align: center + horizon)[#text(weight: "bold")[№]],
      table.cell(fill: rgb("#E2F0D9"), align: left + top)[#text(weight: "bold")[Словосочетание вначале предложения]],
      table.cell(fill: rgb("#E2F0D9"), align: left + top)[#text(weight: "bold")[Подлежащее]],
      table.cell(fill: rgb("#E2F0D9"), align: left + top)[#text(weight: "bold")[Сказуемое]],
      table.cell(fill: rgb("#E2F0D9"), align: left + top)[#text(weight: "bold")[Дополнение]],
      table.cell(fill: rgb("#E2F0D9"), align: left + top)[#text(weight: "bold")[Словосочетание в конце предложения]],
    ),
    table.cell(align: center + horizon, breakable: false)[REQ-001], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Реализуемый веб-сайт], table.cell(align: left + top, breakable: false)[обладает], table.cell(align: left + top, breakable: false)[адаптивно-отзывчивой версткой], table.cell(align: left + top, breakable: false)[обеспечивающей комфортное отображение информации на различных устройствах, принадлежащих трем основным категориям: компьютер, планшет, смартфон],
    table.cell(align: center + horizon, breakable: false)[REQ-002], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Разработанный веб-сайт], table.cell(align: left + top, breakable: false)[должен являться], table.cell(align: left + top, breakable: false)[кроссплатформенным], table.cell(align: left + top, breakable: false)[т. е. должен обладать адекватным отображением контента вне зависимости от операционной системы клиента],
    table.cell(align: center + horizon, breakable: false)[REQ-003], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Разработанный веб-сайт], table.cell(align: left + top, breakable: false)[должен являться], table.cell(align: left + top, breakable: false)[кроссбраузерным], table.cell(align: left + top, breakable: false)[т. е. должен корректно отображаться и функционировать во всех популярных и часто используемых браузерах],
    table.cell(align: center + horizon, breakable: false)[REQ-004], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[должен разрабатываться], table.cell(align: left + top, breakable: false)[с использованием современных технологий и стандартов формата], table.cell(align: left + top, breakable: false)[например стандарта W3C, а также с использованием следующего стека: HTML, CSS, JS (клиентской части)],
    table.cell(align: center + horizon, breakable: false)[REQ-005], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Скорость отклика сайта], table.cell(align: left + top, breakable: false)[должна обеспечивать], table.cell(align: left + top, breakable: false)[обработку данных не менее 5Мб/с], table.cell(align: left + top, breakable: false)[на аппаратном обеспечении, эквивалентном следующему: процессор i7, 8 Гб оперативной памяти],
    table.cell(align: center + horizon, breakable: false)[REQ-006], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Показатель сервиса «Page Speed»], table.cell(align: left + top, breakable: false)[должен находиться], table.cell(align: left + top, breakable: false)[в зеленой зоне], table.cell(align: left + top, breakable: false)[для всех основных критериев анализа веб-сайта, с целью оптимизации скорости, производительности и дальнейшего продвижения],
    table.cell(align: center + horizon, breakable: false)[REQ-007], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[должен демонстрировать], table.cell(align: left + top, breakable: false)[стабильную и производительную работу], table.cell(align: left + top, breakable: false)[с большим потоком пользователей, вне зависимости от вероятных сторонних негативных факторов],
    table.cell(align: center + horizon, breakable: false)[REQ-008], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Возможность отображения информации на веб-сайте], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[на языке комфортном для основной целевой аудитории ресурса; в данном случае необходимо использовать русский и английский язык],
    table.cell(align: center + horizon, breakable: false)[REQ-009], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Возможность быстрого просмотра], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[необходимой информации], table.cell(align: left + top, breakable: false)[],
    table.cell(align: center + horizon, breakable: false)[REQ-010], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Возможность получения], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[какой-либо дополнительной информации], table.cell(align: left + top, breakable: false)[о размещении учебных корпусов, аудиторий и административной информации об образовательном учреждении],
    table.cell(align: center + horizon, breakable: false)[REQ-011], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Редактирование и добавление информации касательно расписаний занятий], table.cell(align: left + top, breakable: false)[допускается], table.cell(align: left + top, breakable: false)[авторизированными пользователями], table.cell(align: left + top, breakable: false)[обладающими правами «Администратора»],
    table.cell(align: center + horizon, breakable: false)[REQ-012], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Разрабатываемое приложение], table.cell(align: left + top, breakable: false)[должны быть защищено и функционировать], table.cell(align: left + top, breakable: false)[в соответствии HTTPS протоколу безопасности передачи данных], table.cell(align: left + top, breakable: false)[],
    table.cell(align: center + horizon, breakable: false)[REQ-013], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Сервис], table.cell(align: left + top, breakable: false)[решает], table.cell(align: left + top, breakable: false)[проблемы заказчика], table.cell(align: left + top, breakable: false)[],
    table.cell(align: center + horizon, breakable: false)[REQ-014], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Сервис], table.cell(align: left + top, breakable: false)[предоставляется], table.cell(align: left + top, breakable: false)[заказчику], table.cell(align: left + top, breakable: false)[в виде лицензии на платформу поставщика или в виде сайта, который заказчик ставит у себя],
  )
]

== Табличное представление требований, шаг 2

#[
  #set text(size: 8pt)
  #set par(justify: false, first-line-indent: (amount: 0pt, all: true), leading: 0.65em, spacing: 0.4em)
  #table(
    columns: (1050fr, 3536fr, 1639fr, 2775fr, 3921fr, 3267fr),
    stroke: 0.5pt,
    inset: 4pt,
    align: left + top,
    table.header(
      repeat: true,
      table.cell(fill: rgb("#FFF2CC"), align: center + horizon)[#text(weight: "bold")[№]],
      table.cell(fill: rgb("#FFF2CC"), align: left + top)[#text(weight: "bold")[Словосочетание вначале предложения]],
      table.cell(fill: rgb("#FFF2CC"), align: left + top)[#text(weight: "bold")[Подлежащее]],
      table.cell(fill: rgb("#FFF2CC"), align: left + top)[#text(weight: "bold")[Сказуемое]],
      table.cell(fill: rgb("#FFF2CC"), align: left + top)[#text(weight: "bold")[Дополнение]],
      table.cell(fill: rgb("#FFF2CC"), align: left + top)[#text(weight: "bold")[Словосочетание в конце предложения]],
    ),
    table.cell(align: center + horizon, breakable: false)[REQ-001], table.cell(align: left + top, breakable: false)[При ширине области просмотра 360 px и более], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[адаптирует], table.cell(align: left + top, breakable: false)[компоновку всех страниц], table.cell(align: left + top, breakable: false)[к диапазонам 360–767 px, 768–1023 px и 1024 px и более без горизонтальной прокрутки страницы],
    table.cell(align: center + horizon, breakable: false)[REQ-002], table.cell(align: left + top, breakable: false)[На поддерживаемых операционных системах], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[обеспечивает], table.cell(align: left + top, breakable: false)[доступность пользовательских функций и корректное отображение интерфейса], table.cell(align: left + top, breakable: false)[на Windows 10/11, macOS 13+, Android 12+ и iOS 16+],
    table.cell(align: center + horizon, breakable: false)[REQ-003], table.cell(align: left + top, breakable: false)[В поддерживаемых браузерах], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[отображает и предоставляет], table.cell(align: left + top, breakable: false)[интерфейс и пользовательские функции], table.cell(align: left + top, breakable: false)[в текущей и предыдущей стабильных версиях Chrome, Edge, Firefox и Safari],
    table.cell(align: center + horizon, breakable: false)[REQ-004], table.cell(align: left + top, breakable: false)[В клиентской части], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[использует], table.cell(align: left + top, breakable: false)[HTML5, CSS и JavaScript стандарта ECMAScript 2015 или новее], table.cell(align: left + top, breakable: false)[с HTML-разметкой, проходящей проверку W3C Markup Validation Service без ошибок],
    table.cell(align: center + horizon, breakable: false)[REQ-005], table.cell(align: left + top, breakable: false)[При нагрузке 100 одновременных пользователей], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[формирует и возвращает], table.cell(align: left + top, breakable: false)[страницу расписания], table.cell(align: left + top, breakable: false)[не более чем за 2 секунды для не менее 95% запросов на заданном тестовом сервере],
    table.cell(align: center + horizon, breakable: false)[REQ-006], table.cell(align: left + top, breakable: false)[При проверке публичных страниц «Главная» и «Расписание»], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[получает], table.cell(align: left + top, breakable: false)[не менее 90 баллов в Google Lighthouse], table.cell(align: left + top, breakable: false)[по категориям Performance, Accessibility, Best Practices и SEO в режимах Mobile и Desktop],
    table.cell(align: center + horizon, breakable: false)[REQ-007], table.cell(align: left + top, breakable: false)[При нагрузочном тестировании в течение 30 минут], table.cell(align: left + top, breakable: false)[Веб-сайт], table.cell(align: left + top, breakable: false)[обслуживает], table.cell(align: left + top, breakable: false)[200 одновременных пользователей], table.cell(align: left + top, breakable: false)[без аварийного завершения серверного приложения и с долей ответов HTTP 5xx не более 1%],
    table.cell(align: center + horizon, breakable: false)[REQ-008], table.cell(align: left + top, breakable: false)[При работе с интерфейсом], table.cell(align: left + top, breakable: false)[Пользователь], table.cell(align: left + top, breakable: false)[выбирает], table.cell(align: left + top, breakable: false)[русский или английский язык], table.cell(align: left + top, breakable: false)[для отображения элементов навигации, подписей полей, кнопок и системных сообщений],
    table.cell(align: center + horizon, breakable: false)[REQ-009], table.cell(align: left + top, breakable: false)[От главной страницы], table.cell(align: left + top, breakable: false)[Пользователь], table.cell(align: left + top, breakable: false)[получает], table.cell(align: left + top, breakable: false)[расписание выбранной учебной группы на выбранную дату], table.cell(align: left + top, breakable: false)[не более чем за три действия интерфейса],
    table.cell(align: center + horizon, breakable: false)[REQ-010], table.cell(align: left + top, breakable: false)[При просмотре справочной информации], table.cell(align: left + top, breakable: false)[Пользователь], table.cell(align: left + top, breakable: false)[просматривает], table.cell(align: left + top, breakable: false)[название и адрес учебного корпуса, номер аудитории, телефон и электронную почту администрации], table.cell(align: left + top, breakable: false)[в веб-сайте],
    table.cell(align: center + horizon, breakable: false)[REQ-011], table.cell(align: left + top, breakable: false)[После успешной аутентификации], table.cell(align: left + top, breakable: false)[Пользователь с ролью «Администратор»], table.cell(align: left + top, breakable: false)[добавляет и редактирует], table.cell(align: left + top, breakable: false)[информацию о расписании], table.cell(align: left + top, breakable: false)[при наличии административных прав],
    table.cell(align: center + horizon, breakable: false)[REQ-012], table.cell(align: left + top, breakable: false)[При любом клиент-серверном обмене], table.cell(align: left + top, breakable: false)[Система], table.cell(align: left + top, breakable: false)[передает], table.cell(align: left + top, breakable: false)[данные между клиентом и сервером], table.cell(align: left + top, breakable: false)[по HTTPS с TLS 1.2 или новее и перенаправляет обращения по HTTP на HTTPS],
    table.cell(align: center + horizon, breakable: false)[REQ-013], table.cell(align: left + top, breakable: false)[], table.cell(align: left + top, breakable: false)[Система], table.cell(align: left + top, breakable: false)[предоставляет], table.cell(align: left + top, breakable: false)[актуальное расписание занятий], table.cell(align: left + top, breakable: false)[университетам, школам, в том числе онлайн-школам, и колледжам],
    table.cell(align: center + horizon, breakable: false)[REQ-014], table.cell(align: left + top, breakable: false)[При поставке], table.cell(align: left + top, breakable: false)[Заказчик], table.cell(align: left + top, breakable: false)[устанавливает], table.cell(align: left + top, breakable: false)[сайт сервиса], table.cell(align: left + top, breakable: false)[на своей площадке, без лицензии на платформу у поставщика],
  )
]
